/* tslint:disable */
/* eslint-disable */
/**
 * CryptoGate API
 * Accept Bitcoin, Litecoin, Dogecoin, Dash, Ethereum and ERC-20 tokens. Server-to-server, authenticated with a secret API key (`Authorization: Bearer sk_live_…`, or `sk_test_…` for sandbox). All monetary amounts in API responses are JSON numbers; **webhook** amounts are strings to preserve decimal precision (see the `webhooks` section).  **Rate limits.** Every request is rate-limited per API key in two windows — per minute and per hour — by plan tier (min/hour): starter 30/500, business 100/2000, professional 300/5000, enterprise 1000/20000. Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (Unix seconds) for the per-minute window. On `429` the body is `error: \"RATE_LIMIT_EXCEEDED\"` (either window) with a `Retry-After` header (seconds) — clients should retry after it. A separate `429` with `error: \"MONTHLY_LIMIT_REACHED\"` means the plan\'s monthly transaction quota (not the request rate). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {AccountPlan}
     * @memberof Account
     */
    'plan'?: AccountPlan;
    /**
     * 
     * @type {AccountUsage}
     * @memberof Account
     */
    'usage'?: AccountUsage;
    /**
     * 
     * @type {AccountLimits}
     * @memberof Account
     */
    'limits'?: AccountLimits;
}
/**
 * 
 * @export
 * @interface AccountLimits
 */
export interface AccountLimits {
    /**
     * 
     * @type {number}
     * @memberof AccountLimits
     */
    'api_rate_limit_per_minute'?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountLimits
     */
    'api_rate_limit_per_hour'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AccountLimits
     */
    'webhook_support'?: boolean;
}
/**
 * 
 * @export
 * @interface AccountPlan
 */
export interface AccountPlan {
    /**
     * 
     * @type {PlanTier}
     * @memberof AccountPlan
     */
    'tier'?: PlanTier;
    /**
     * 
     * @type {string}
     * @memberof AccountPlan
     */
    'billing_cycle'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AccountPlan
     */
    'auto_renewal'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AccountPlan
     */
    'expires_at'?: string | null;
}


/**
 * 
 * @export
 * @interface AccountUsage
 */
export interface AccountUsage {
    /**
     * 
     * @type {number}
     * @memberof AccountUsage
     */
    'monthly_transactions_used'?: number;
    /**
     * null = unlimited.
     * @type {number}
     * @memberof AccountUsage
     */
    'monthly_transaction_limit'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AccountUsage
     */
    'overage_cost_per_tx'?: number;
}
/**
 * 
 * @export
 * @interface Balance
 */
export interface Balance {
    /**
     * 
     * @type {string}
     * @memberof Balance
     */
    'currency'?: string;
    /**
     * 
     * @type {number}
     * @memberof Balance
     */
    'available_balance'?: number;
    /**
     * 
     * @type {number}
     * @memberof Balance
     */
    'pending_balance'?: number;
    /**
     * 
     * @type {string}
     * @memberof Balance
     */
    'updated_at'?: string;
}
/**
 * 
 * @export
 * @interface CreateBillingCheckoutRequest
 */
export interface CreateBillingCheckoutRequest {
    /**
     * 
     * @type {PlanTier}
     * @memberof CreateBillingCheckoutRequest
     */
    'tier': PlanTier;
    /**
     * 
     * @type {number}
     * @memberof CreateBillingCheckoutRequest
     */
    'billing_months'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateBillingCheckoutRequest
     */
    'payment_method'?: string;
}


/**
 * 
 * @export
 * @interface CreateDetailedTransactionRequest
 */
export interface CreateDetailedTransactionRequest {
    /**
     * 
     * @type {CryptoSymbol}
     * @memberof CreateDetailedTransactionRequest
     */
    'crypto': CryptoSymbol;
    /**
     * 
     * @type {FiatCurrency}
     * @memberof CreateDetailedTransactionRequest
     */
    'currency_fiat'?: FiatCurrency;
    /**
     * 
     * @type {Array<LineItem>}
     * @memberof CreateDetailedTransactionRequest
     */
    'items': Array<LineItem>;
    /**
     * 
     * @type {string}
     * @memberof CreateDetailedTransactionRequest
     */
    'order_id': string;
    /**
     * Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
     * @type {{ [key: string]: string; }}
     * @memberof CreateDetailedTransactionRequest
     */
    'metadata'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof CreateDetailedTransactionRequest
     */
    'customer_email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateDetailedTransactionRequest
     */
    'success_url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateDetailedTransactionRequest
     */
    'cancel_url'?: string | null;
}


/**
 * 
 * @export
 * @interface CreateTransactionRequest
 */
export interface CreateTransactionRequest {
    /**
     * 
     * @type {CryptoSymbol}
     * @memberof CreateTransactionRequest
     */
    'crypto': CryptoSymbol;
    /**
     * Fiat amount (≥ 1.00 USD equivalent).
     * @type {number}
     * @memberof CreateTransactionRequest
     */
    'amount': number;
    /**
     * 
     * @type {FiatCurrency}
     * @memberof CreateTransactionRequest
     */
    'currency_fiat'?: FiatCurrency;
    /**
     * Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
     * @type {{ [key: string]: string; }}
     * @memberof CreateTransactionRequest
     */
    'metadata'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof CreateTransactionRequest
     */
    'customer_email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateTransactionRequest
     */
    'success_url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateTransactionRequest
     */
    'cancel_url'?: string | null;
}


/**
 * Supported coin/token symbol. /cryptos/list is authoritative at runtime.
 * @export
 * @enum {string}
 */

export const CryptoSymbol = {
    Btc: 'BTC',
    Ltc: 'LTC',
    Doge: 'DOGE',
    Dash: 'DASH',
    Eth: 'ETH',
    Usdt: 'USDT',
    Usdc: 'USDC',
    Dai: 'DAI',
    Wbtc: 'WBTC',
    Shib: 'SHIB',
    Pepe: 'PEPE',
    Link: 'LINK',
    Uni: 'UNI',
    Aave: 'AAVE',
    Mkr: 'MKR'
} as const;

export type CryptoSymbol = typeof CryptoSymbol[keyof typeof CryptoSymbol];


/**
 * 
 * @export
 * @interface Cryptocurrency
 */
export interface Cryptocurrency {
    /**
     * 
     * @type {CryptoSymbol}
     * @memberof Cryptocurrency
     */
    'symbol'?: CryptoSymbol;
    /**
     * 
     * @type {string}
     * @memberof Cryptocurrency
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Cryptocurrency
     */
    'blockchain'?: string;
    /**
     * 
     * @type {string}
     * @memberof Cryptocurrency
     */
    'network'?: string;
    /**
     * 
     * @type {string}
     * @memberof Cryptocurrency
     */
    'type'?: CryptocurrencyTypeEnum;
}

export const CryptocurrencyTypeEnum = {
    Coin: 'coin',
    Token: 'token'
} as const;

export type CryptocurrencyTypeEnum = typeof CryptocurrencyTypeEnum[keyof typeof CryptocurrencyTypeEnum];

/**
 * 
 * @export
 * @enum {string}
 */

export const FiatCurrency = {
    Usd: 'USD',
    Pln: 'PLN',
    Eur: 'EUR',
    Gbp: 'GBP'
} as const;

export type FiatCurrency = typeof FiatCurrency[keyof typeof FiatCurrency];


/**
 * 
 * @export
 * @interface GetAccount200Response
 */
export interface GetAccount200Response {
    /**
     * 
     * @type {any}
     * @memberof GetAccount200Response
     */
    'success': any;
    /**
     * 
     * @type {Account}
     * @memberof GetAccount200Response
     */
    'data': Account;
}
/**
 * 
 * @export
 * @interface GetHealth200Response
 */
export interface GetHealth200Response {
    /**
     * 
     * @type {string}
     * @memberof GetHealth200Response
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetHealth200Response
     */
    'service'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetHealth200Response
     */
    'version'?: string;
}
/**
 * 
 * @export
 * @interface GetPrices200Response
 */
export interface GetPrices200Response {
    /**
     * 
     * @type {any}
     * @memberof GetPrices200Response
     */
    'success': any;
    /**
     * 
     * @type {GetPrices200ResponseData}
     * @memberof GetPrices200Response
     */
    'data': GetPrices200ResponseData;
}
/**
 * 
 * @export
 * @interface GetPrices200ResponseData
 */
export interface GetPrices200ResponseData {
    /**
     * USD price per unit, keyed by crypto symbol (active coins only).
     * @type {{ [key: string]: number; }}
     * @memberof GetPrices200ResponseData
     */
    'crypto'?: { [key: string]: number; };
    /**
     * USD value of one unit of each fiat currency.
     * @type {{ [key: string]: number; }}
     * @memberof GetPrices200ResponseData
     */
    'fiat'?: { [key: string]: number; };
    /**
     * 
     * @type {string}
     * @memberof GetPrices200ResponseData
     */
    'fetched_at'?: string;
}
/**
 * 
 * @export
 * @interface GetStats200Response
 */
export interface GetStats200Response {
    /**
     * 
     * @type {any}
     * @memberof GetStats200Response
     */
    'success': any;
    /**
     * 
     * @type {GetStats200ResponseData}
     * @memberof GetStats200Response
     */
    'data': GetStats200ResponseData;
}
/**
 * 
 * @export
 * @interface GetStats200ResponseData
 */
export interface GetStats200ResponseData {
    /**
     * 
     * @type {number}
     * @memberof GetStats200ResponseData
     */
    'total_transactions'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetStats200ResponseData
     */
    'monthly_transactions'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetStats200ResponseData
     */
    'total_volume_fiat'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetStats200ResponseData
     */
    'unique_customers'?: number;
}
/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {any}
     * @memberof InlineObject
     */
    'success': any;
    /**
     * Machine-readable code.
     * @type {string}
     * @memberof InlineObject
     */
    'error': string;
    /**
     * Human-readable description.
     * @type {string}
     * @memberof InlineObject
     */
    'message': string;
    /**
     * 
     * @type {InlineObjectAllOfExistingTransaction}
     * @memberof InlineObject
     */
    'existing_transaction'?: InlineObjectAllOfExistingTransaction;
}
/**
 * 
 * @export
 * @interface InlineObjectAllOfExistingTransaction
 */
export interface InlineObjectAllOfExistingTransaction {
    /**
     * 
     * @type {string}
     * @memberof InlineObjectAllOfExistingTransaction
     */
    'transaction_id'?: string;
    /**
     * 
     * @type {TransactionStatus}
     * @memberof InlineObjectAllOfExistingTransaction
     */
    'status'?: TransactionStatus;
    /**
     * 
     * @type {string}
     * @memberof InlineObjectAllOfExistingTransaction
     */
    'payment_url'?: string;
}


/**
 * 
 * @export
 * @interface Invoice
 */
export interface Invoice {
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'transaction_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'purchase_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    'amount_fiat'?: number;
    /**
     * 
     * @type {FiatCurrency}
     * @memberof Invoice
     */
    'currency_fiat'?: FiatCurrency;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'status'?: string;
    /**
     * 
     * @type {CryptoSymbol}
     * @memberof Invoice
     */
    'crypto_symbol'?: CryptoSymbol;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'confirmed_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'expires_at'?: string;
}


/**
 * 
 * @export
 * @interface LineItem
 */
export interface LineItem {
    /**
     * 
     * @type {string}
     * @memberof LineItem
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof LineItem
     */
    'quantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof LineItem
     */
    'price': number;
}
/**
 * 
 * @export
 * @interface ListBalances200Response
 */
export interface ListBalances200Response {
    /**
     * 
     * @type {any}
     * @memberof ListBalances200Response
     */
    'success': any;
    /**
     * 
     * @type {ListBalances200ResponseData}
     * @memberof ListBalances200Response
     */
    'data': ListBalances200ResponseData;
}
/**
 * 
 * @export
 * @interface ListBalances200ResponseData
 */
export interface ListBalances200ResponseData {
    /**
     * 
     * @type {Array<Balance>}
     * @memberof ListBalances200ResponseData
     */
    'balances'?: Array<Balance>;
}
/**
 * 
 * @export
 * @interface ListCryptocurrencies200Response
 */
export interface ListCryptocurrencies200Response {
    /**
     * 
     * @type {any}
     * @memberof ListCryptocurrencies200Response
     */
    'success': any;
    /**
     * 
     * @type {ListCryptocurrencies200ResponseData}
     * @memberof ListCryptocurrencies200Response
     */
    'data': ListCryptocurrencies200ResponseData;
}
/**
 * 
 * @export
 * @interface ListCryptocurrencies200ResponseData
 */
export interface ListCryptocurrencies200ResponseData {
    /**
     * 
     * @type {Array<Cryptocurrency>}
     * @memberof ListCryptocurrencies200ResponseData
     */
    'cryptocurrencies'?: Array<Cryptocurrency>;
    /**
     * 
     * @type {number}
     * @memberof ListCryptocurrencies200ResponseData
     */
    'total'?: number;
}
/**
 * 
 * @export
 * @interface ListInvoices200Response
 */
export interface ListInvoices200Response {
    /**
     * 
     * @type {any}
     * @memberof ListInvoices200Response
     */
    'success': any;
    /**
     * 
     * @type {ListInvoices200ResponseData}
     * @memberof ListInvoices200Response
     */
    'data': ListInvoices200ResponseData;
}
/**
 * 
 * @export
 * @interface ListInvoices200ResponseData
 */
export interface ListInvoices200ResponseData {
    /**
     * 
     * @type {Array<Invoice>}
     * @memberof ListInvoices200ResponseData
     */
    'invoices'?: Array<Invoice>;
    /**
     * 
     * @type {Pagination}
     * @memberof ListInvoices200ResponseData
     */
    'pagination'?: Pagination;
}
/**
 * 
 * @export
 * @interface ListPlans200Response
 */
export interface ListPlans200Response {
    /**
     * 
     * @type {any}
     * @memberof ListPlans200Response
     */
    'success': any;
    /**
     * 
     * @type {ListPlans200ResponseData}
     * @memberof ListPlans200Response
     */
    'data': ListPlans200ResponseData;
}
/**
 * 
 * @export
 * @interface ListPlans200ResponseData
 */
export interface ListPlans200ResponseData {
    /**
     * 
     * @type {Array<Plan>}
     * @memberof ListPlans200ResponseData
     */
    'plans'?: Array<Plan>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListPlans200ResponseData
     */
    'billing_cycles'?: Array<string>;
}
/**
 * 
 * @export
 * @interface ListTransactions200Response
 */
export interface ListTransactions200Response {
    /**
     * 
     * @type {any}
     * @memberof ListTransactions200Response
     */
    'success': any;
    /**
     * 
     * @type {ListTransactions200ResponseData}
     * @memberof ListTransactions200Response
     */
    'data': ListTransactions200ResponseData;
}
/**
 * 
 * @export
 * @interface ListTransactions200ResponseData
 */
export interface ListTransactions200ResponseData {
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof ListTransactions200ResponseData
     */
    'transactions': Array<Transaction>;
    /**
     * 
     * @type {Pagination}
     * @memberof ListTransactions200ResponseData
     */
    'pagination': Pagination;
}
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {any}
     * @memberof ModelError
     */
    'success': any;
    /**
     * Machine-readable code.
     * @type {string}
     * @memberof ModelError
     */
    'error': string;
    /**
     * Human-readable description.
     * @type {string}
     * @memberof ModelError
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'limit': number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'offset': number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    'total': number;
}
/**
 * One on-chain payment toward the transaction.
 * @export
 * @interface PaymentSplit
 */
export interface PaymentSplit {
    /**
     * On-chain transaction hash (blockchain id, NOT the CryptoGate transaction_id).
     * @type {string}
     * @memberof PaymentSplit
     */
    'txid'?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentSplit
     */
    'amount_crypto'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentSplit
     */
    'confirmations'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentSplit
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentSplit
     */
    'detected_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentSplit
     */
    'confirmed_at'?: string | null;
}
/**
 * 
 * @export
 * @interface Plan
 */
export interface Plan {
    /**
     * 
     * @type {PlanTier}
     * @memberof Plan
     */
    'tier'?: PlanTier;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    'monthly_price_usd'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    'yearly_price_usd'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    'monthly_transaction_limit'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    'overage_cost_per_tx'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Plan
     */
    'webhook_support'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    'webhook_limit'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Plan
     */
    'ip_whitelist'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    'api_rate_limit_per_minute'?: number;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    'api_rate_limit_per_hour'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Plan
     */
    'custom_pricing'?: boolean;
}


/**
 * 
 * @export
 * @enum {string}
 */

export const PlanTier = {
    Starter: 'starter',
    Business: 'business',
    Professional: 'professional',
    Enterprise: 'enterprise'
} as const;

export type PlanTier = typeof PlanTier[keyof typeof PlanTier];


/**
 * The canonical, curated public view of a transaction (same shape from create, get and list). Internal fields (capability tokens, client_ip, address_index, derivation/db internals) are deliberately NOT exposed. 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'transaction_id': string;
    /**
     * 
     * @type {TransactionStatus}
     * @memberof Transaction
     */
    'status': TransactionStatus;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'type'?: TransactionTypeEnum;
    /**
     * 
     * @type {CryptoSymbol}
     * @memberof Transaction
     */
    'crypto': CryptoSymbol;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'deposit_address'?: string;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'amount_crypto'?: number;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'amount_fiat': number;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'amount_usd': number;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'amount_paid'?: number;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'amount_remaining'?: number;
    /**
     * 
     * @type {FiatCurrency}
     * @memberof Transaction
     */
    'currency_fiat': FiatCurrency;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'fiat_to_usd_rate'?: number;
    /**
     * USD per unit of crypto, locked at creation.
     * @type {number}
     * @memberof Transaction
     */
    'exchange_rate'?: number;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'confirmations_required'?: number;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'payment_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'order_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'customer_email'?: string | null;
    /**
     * 
     * @type {Array<LineItem>}
     * @memberof Transaction
     */
    'items'?: Array<LineItem> | null;
    /**
     * On-chain payments detected toward this transaction.
     * @type {Array<PaymentSplit>}
     * @memberof Transaction
     */
    'payments'?: Array<PaymentSplit>;
    /**
     * Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
     * @type {{ [key: string]: string; }}
     * @memberof Transaction
     */
    'metadata'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'success_url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'cancel_url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'expires_at': string;
}

export const TransactionTypeEnum = {
    Basic: 'basic',
    Detailed: 'detailed'
} as const;

export type TransactionTypeEnum = typeof TransactionTypeEnum[keyof typeof TransactionTypeEnum];

/**
 * 
 * @export
 * @interface TransactionEnvelope
 */
export interface TransactionEnvelope {
    /**
     * 
     * @type {any}
     * @memberof TransactionEnvelope
     */
    'success': any;
    /**
     * 
     * @type {Transaction}
     * @memberof TransactionEnvelope
     */
    'data': Transaction;
}
/**
 * Public transaction status (internal sub-states are mapped to these).
 * @export
 * @enum {string}
 */

export const TransactionStatus = {
    Pending: 'pending',
    AwaitingConfirmation: 'awaiting_confirmation',
    Completed: 'completed',
    Partial: 'partial',
    Expired: 'expired',
    Failed: 'failed'
} as const;

export type TransactionStatus = typeof TransactionStatus[keyof typeof TransactionStatus];


/**
 * Payment-event payload. AMOUNTS ARE STRINGS (e.g. \"100.00\", \"0.00109462\") to preserve decimal precision — parse before arithmetic. 
 * @export
 * @interface WebhookPayload
 */
export interface WebhookPayload {
    /**
     * 
     * @type {string}
     * @memberof WebhookPayload
     */
    'event': WebhookPayloadEventEnum;
    /**
     * 
     * @type {string}
     * @memberof WebhookPayload
     */
    'timestamp': string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPayload
     */
    'transaction_id': string;
    /**
     * 
     * @type {TransactionStatus}
     * @memberof WebhookPayload
     */
    'status': TransactionStatus;
    /**
     * 
     * @type {CryptoSymbol}
     * @memberof WebhookPayload
     */
    'currency_crypto'?: CryptoSymbol;
    /**
     * 
     * @type {FiatCurrency}
     * @memberof WebhookPayload
     */
    'currency_fiat'?: FiatCurrency;
    /**
     * Decimal string.
     * @type {string}
     * @memberof WebhookPayload
     */
    'amount_fiat'?: string;
    /**
     * Decimal string.
     * @type {string}
     * @memberof WebhookPayload
     */
    'amount_usd'?: string;
    /**
     * Decimal string.
     * @type {string}
     * @memberof WebhookPayload
     */
    'amount_crypto'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookPayload
     */
    'order_id'?: string | null;
    /**
     * Present on completed/overpaid.
     * @type {string}
     * @memberof WebhookPayload
     */
    'receipt_url'?: string | null;
    /**
     * Free-form key/value (≤20 keys, string values ≤500 chars, ≤4 KB total).
     * @type {{ [key: string]: string; }}
     * @memberof WebhookPayload
     */
    'metadata'?: { [key: string]: string; };
}

export const WebhookPayloadEventEnum = {
    Created: 'payment.created',
    Pending: 'payment.pending',
    Completed: 'payment.completed',
    Overpaid: 'payment.overpaid',
    Partial: 'payment.partial',
    Expired: 'payment.expired',
    Failed: 'payment.failed'
} as const;

export type WebhookPayloadEventEnum = typeof WebhookPayloadEventEnum[keyof typeof WebhookPayloadEventEnum];


/**
 * AccountApi - axios parameter creator
 * @export
 */
export const AccountApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Merchant plan, usage and limits
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccount: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/account`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecretKey required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Merchant transaction analytics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStats: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecretKey required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary On-platform balances (for overage/top-up; NOT crypto settlement)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBalances: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/balances`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecretKey required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary CryptoGate billing invoices (platform ↔ merchant)
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInvoices: async (limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/invoices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecretKey required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Plan catalogue and pricing
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPlans: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/plans`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecretKey required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccountApi - functional programming interface
 * @export
 */
export const AccountApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccountApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Merchant plan, usage and limits
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAccount(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAccount200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAccount(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.getAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Merchant transaction analytics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStats(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetStats200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStats(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.getStats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary On-platform balances (for overage/top-up; NOT crypto settlement)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBalances(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListBalances200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBalances(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.listBalances']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary CryptoGate billing invoices (platform ↔ merchant)
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listInvoices(limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListInvoices200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listInvoices(limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.listInvoices']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Plan catalogue and pricing
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPlans(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListPlans200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPlans(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.listPlans']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AccountApi - factory interface
 * @export
 */
export const AccountApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccountApiFp(configuration)
    return {
        /**
         * 
         * @summary Merchant plan, usage and limits
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAccount(options?: RawAxiosRequestConfig): AxiosPromise<GetAccount200Response> {
            return localVarFp.getAccount(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Merchant transaction analytics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStats(options?: RawAxiosRequestConfig): AxiosPromise<GetStats200Response> {
            return localVarFp.getStats(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary On-platform balances (for overage/top-up; NOT crypto settlement)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBalances(options?: RawAxiosRequestConfig): AxiosPromise<ListBalances200Response> {
            return localVarFp.listBalances(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary CryptoGate billing invoices (platform ↔ merchant)
         * @param {AccountApiListInvoicesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInvoices(requestParameters: AccountApiListInvoicesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ListInvoices200Response> {
            return localVarFp.listInvoices(requestParameters.limit, requestParameters.offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Plan catalogue and pricing
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPlans(options?: RawAxiosRequestConfig): AxiosPromise<ListPlans200Response> {
            return localVarFp.listPlans(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for listInvoices operation in AccountApi.
 * @export
 * @interface AccountApiListInvoicesRequest
 */
export interface AccountApiListInvoicesRequest {
    /**
     * 
     * @type {number}
     * @memberof AccountApiListInvoices
     */
    readonly limit?: number

    /**
     * 
     * @type {number}
     * @memberof AccountApiListInvoices
     */
    readonly offset?: number
}

/**
 * AccountApi - object-oriented interface
 * @export
 * @class AccountApi
 * @extends {BaseAPI}
 */
export class AccountApi extends BaseAPI {
    /**
     * 
     * @summary Merchant plan, usage and limits
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public getAccount(options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).getAccount(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Merchant transaction analytics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public getStats(options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).getStats(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary On-platform balances (for overage/top-up; NOT crypto settlement)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public listBalances(options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).listBalances(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary CryptoGate billing invoices (platform ↔ merchant)
     * @param {AccountApiListInvoicesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public listInvoices(requestParameters: AccountApiListInvoicesRequest = {}, options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).listInvoices(requestParameters.limit, requestParameters.offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Plan catalogue and pricing
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public listPlans(options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).listPlans(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * BillingApi - axios parameter creator
 * @export
 */
export const BillingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Start a plan upgrade or account top-up
         * @param {CreateBillingCheckoutRequest} createBillingCheckoutRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBillingCheckout: async (createBillingCheckoutRequest: CreateBillingCheckoutRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createBillingCheckoutRequest' is not null or undefined
            assertParamExists('createBillingCheckout', 'createBillingCheckoutRequest', createBillingCheckoutRequest)
            const localVarPath = `/billing/checkout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecretKey required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createBillingCheckoutRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BillingApi - functional programming interface
 * @export
 */
export const BillingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BillingApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Start a plan upgrade or account top-up
         * @param {CreateBillingCheckoutRequest} createBillingCheckoutRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBillingCheckout(createBillingCheckoutRequest: CreateBillingCheckoutRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createBillingCheckout(createBillingCheckoutRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BillingApi.createBillingCheckout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BillingApi - factory interface
 * @export
 */
export const BillingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BillingApiFp(configuration)
    return {
        /**
         * 
         * @summary Start a plan upgrade or account top-up
         * @param {BillingApiCreateBillingCheckoutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBillingCheckout(requestParameters: BillingApiCreateBillingCheckoutRequest, options?: RawAxiosRequestConfig): AxiosPromise<TransactionEnvelope> {
            return localVarFp.createBillingCheckout(requestParameters.createBillingCheckoutRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createBillingCheckout operation in BillingApi.
 * @export
 * @interface BillingApiCreateBillingCheckoutRequest
 */
export interface BillingApiCreateBillingCheckoutRequest {
    /**
     * 
     * @type {CreateBillingCheckoutRequest}
     * @memberof BillingApiCreateBillingCheckout
     */
    readonly createBillingCheckoutRequest: CreateBillingCheckoutRequest
}

/**
 * BillingApi - object-oriented interface
 * @export
 * @class BillingApi
 * @extends {BaseAPI}
 */
export class BillingApi extends BaseAPI {
    /**
     * 
     * @summary Start a plan upgrade or account top-up
     * @param {BillingApiCreateBillingCheckoutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApi
     */
    public createBillingCheckout(requestParameters: BillingApiCreateBillingCheckoutRequest, options?: RawAxiosRequestConfig) {
        return BillingApiFp(this.configuration).createBillingCheckout(requestParameters.createBillingCheckoutRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MarketDataApi - axios parameter creator
 * @export
 */
export const MarketDataApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Current crypto and fiat exchange rates (USD-denominated)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPrices: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/prices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecretKey required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary All supported cryptocurrencies and tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCryptocurrencies: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cryptos/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecretKey required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cryptocurrencies this merchant has wallets configured for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMerchantCryptocurrencies: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/merchant/cryptos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecretKey required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MarketDataApi - functional programming interface
 * @export
 */
export const MarketDataApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MarketDataApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Current crypto and fiat exchange rates (USD-denominated)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPrices(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetPrices200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPrices(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MarketDataApi.getPrices']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary All supported cryptocurrencies and tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCryptocurrencies(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListCryptocurrencies200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listCryptocurrencies(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MarketDataApi.listCryptocurrencies']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Cryptocurrencies this merchant has wallets configured for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMerchantCryptocurrencies(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListCryptocurrencies200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMerchantCryptocurrencies(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MarketDataApi.listMerchantCryptocurrencies']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MarketDataApi - factory interface
 * @export
 */
export const MarketDataApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MarketDataApiFp(configuration)
    return {
        /**
         * 
         * @summary Current crypto and fiat exchange rates (USD-denominated)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPrices(options?: RawAxiosRequestConfig): AxiosPromise<GetPrices200Response> {
            return localVarFp.getPrices(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary All supported cryptocurrencies and tokens
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCryptocurrencies(options?: RawAxiosRequestConfig): AxiosPromise<ListCryptocurrencies200Response> {
            return localVarFp.listCryptocurrencies(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cryptocurrencies this merchant has wallets configured for
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMerchantCryptocurrencies(options?: RawAxiosRequestConfig): AxiosPromise<ListCryptocurrencies200Response> {
            return localVarFp.listMerchantCryptocurrencies(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MarketDataApi - object-oriented interface
 * @export
 * @class MarketDataApi
 * @extends {BaseAPI}
 */
export class MarketDataApi extends BaseAPI {
    /**
     * 
     * @summary Current crypto and fiat exchange rates (USD-denominated)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MarketDataApi
     */
    public getPrices(options?: RawAxiosRequestConfig) {
        return MarketDataApiFp(this.configuration).getPrices(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary All supported cryptocurrencies and tokens
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MarketDataApi
     */
    public listCryptocurrencies(options?: RawAxiosRequestConfig) {
        return MarketDataApiFp(this.configuration).listCryptocurrencies(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cryptocurrencies this merchant has wallets configured for
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MarketDataApi
     */
    public listMerchantCryptocurrencies(options?: RawAxiosRequestConfig) {
        return MarketDataApiFp(this.configuration).listMerchantCryptocurrencies(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SystemApi - axios parameter creator
 * @export
 */
export const SystemApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary API health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHealth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
         * @summary Hosted-checkout redirect (browser flow, publishable key)
         * @param {string} pk Publishable key, pk_live_… / pk_test_…
         * @param {string} amount Fiat amount (≥ 1.00 USD equivalent).
         * @param {CryptoSymbol} crypto 
         * @param {string} [link] Payment-link slug for attribution.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hostedCheckoutRedirect: async (pk: string, amount: string, crypto: CryptoSymbol, link?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pk' is not null or undefined
            assertParamExists('hostedCheckoutRedirect', 'pk', pk)
            // verify required parameter 'amount' is not null or undefined
            assertParamExists('hostedCheckoutRedirect', 'amount', amount)
            // verify required parameter 'crypto' is not null or undefined
            assertParamExists('hostedCheckoutRedirect', 'crypto', crypto)
            const localVarPath = `/pay`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (pk !== undefined) {
                localVarQueryParameter['pk'] = pk;
            }

            if (amount !== undefined) {
                localVarQueryParameter['amount'] = amount;
            }

            if (crypto !== undefined) {
                localVarQueryParameter['crypto'] = crypto;
            }

            if (link !== undefined) {
                localVarQueryParameter['link'] = link;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemApi - functional programming interface
 * @export
 */
export const SystemApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary API health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHealth(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetHealth200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHealth(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemApi.getHealth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
         * @summary Hosted-checkout redirect (browser flow, publishable key)
         * @param {string} pk Publishable key, pk_live_… / pk_test_…
         * @param {string} amount Fiat amount (≥ 1.00 USD equivalent).
         * @param {CryptoSymbol} crypto 
         * @param {string} [link] Payment-link slug for attribution.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hostedCheckoutRedirect(pk: string, amount: string, crypto: CryptoSymbol, link?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hostedCheckoutRedirect(pk, amount, crypto, link, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SystemApi.hostedCheckoutRedirect']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SystemApi - factory interface
 * @export
 */
export const SystemApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemApiFp(configuration)
    return {
        /**
         * 
         * @summary API health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHealth(options?: RawAxiosRequestConfig): AxiosPromise<GetHealth200Response> {
            return localVarFp.getHealth(options).then((request) => request(axios, basePath));
        },
        /**
         * Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
         * @summary Hosted-checkout redirect (browser flow, publishable key)
         * @param {SystemApiHostedCheckoutRedirectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hostedCheckoutRedirect(requestParameters: SystemApiHostedCheckoutRedirectRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.hostedCheckoutRedirect(requestParameters.pk, requestParameters.amount, requestParameters.crypto, requestParameters.link, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for hostedCheckoutRedirect operation in SystemApi.
 * @export
 * @interface SystemApiHostedCheckoutRedirectRequest
 */
export interface SystemApiHostedCheckoutRedirectRequest {
    /**
     * Publishable key, pk_live_… / pk_test_…
     * @type {string}
     * @memberof SystemApiHostedCheckoutRedirect
     */
    readonly pk: string

    /**
     * Fiat amount (≥ 1.00 USD equivalent).
     * @type {string}
     * @memberof SystemApiHostedCheckoutRedirect
     */
    readonly amount: string

    /**
     * 
     * @type {CryptoSymbol}
     * @memberof SystemApiHostedCheckoutRedirect
     */
    readonly crypto: CryptoSymbol

    /**
     * Payment-link slug for attribution.
     * @type {string}
     * @memberof SystemApiHostedCheckoutRedirect
     */
    readonly link?: string
}

/**
 * SystemApi - object-oriented interface
 * @export
 * @class SystemApi
 * @extends {BaseAPI}
 */
export class SystemApi extends BaseAPI {
    /**
     * 
     * @summary API health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApi
     */
    public getHealth(options?: RawAxiosRequestConfig) {
        return SystemApiFp(this.configuration).getHealth(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Browser-facing redirect to the hosted payment page, authenticated by a **publishable** key in the query string (safe to expose client-side). Not used by the server-side SDKs — included for completeness. 
     * @summary Hosted-checkout redirect (browser flow, publishable key)
     * @param {SystemApiHostedCheckoutRedirectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApi
     */
    public hostedCheckoutRedirect(requestParameters: SystemApiHostedCheckoutRedirectRequest, options?: RawAxiosRequestConfig) {
        return SystemApiFp(this.configuration).hostedCheckoutRedirect(requestParameters.pk, requestParameters.amount, requestParameters.crypto, requestParameters.link, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TransactionsApi - axios parameter creator
 * @export
 */
export const TransactionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create an itemized transaction (Professional/Enterprise plans)
         * @param {CreateDetailedTransactionRequest} createDetailedTransactionRequest 
         * @param {string} [xIdempotencyKey] Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can\&#39;t double-charge the customer. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDetailedTransaction: async (createDetailedTransactionRequest: CreateDetailedTransactionRequest, xIdempotencyKey?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createDetailedTransactionRequest' is not null or undefined
            assertParamExists('createDetailedTransaction', 'createDetailedTransactionRequest', createDetailedTransactionRequest)
            const localVarPath = `/transactions/create-detailed`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecretKey required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xIdempotencyKey != null) {
                localVarHeaderParameter['X-Idempotency-Key'] = String(xIdempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createDetailedTransactionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a payment transaction
         * @param {CreateTransactionRequest} createTransactionRequest 
         * @param {string} [xIdempotencyKey] Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can\&#39;t double-charge the customer. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTransaction: async (createTransactionRequest: CreateTransactionRequest, xIdempotencyKey?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createTransactionRequest' is not null or undefined
            assertParamExists('createTransaction', 'createTransactionRequest', createTransactionRequest)
            const localVarPath = `/transactions/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecretKey required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xIdempotencyKey != null) {
                localVarHeaderParameter['X-Idempotency-Key'] = String(xIdempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTransactionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieve a single transaction
         * @param {string} transactionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransaction: async (transactionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'transactionId' is not null or undefined
            assertParamExists('getTransaction', 'transactionId', transactionId)
            const localVarPath = `/transactions/{transaction_id}`
                .replace(`{${"transaction_id"}}`, encodeURIComponent(String(transactionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecretKey required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List the merchant\'s transactions (newest first)
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {TransactionStatus} [status] 
         * @param {CryptoSymbol} [crypto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTransactions: async (limit?: number, offset?: number, status?: TransactionStatus, crypto?: CryptoSymbol, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/transactions/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SecretKey required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (crypto !== undefined) {
                localVarQueryParameter['crypto'] = crypto;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionsApi - functional programming interface
 * @export
 */
export const TransactionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransactionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create an itemized transaction (Professional/Enterprise plans)
         * @param {CreateDetailedTransactionRequest} createDetailedTransactionRequest 
         * @param {string} [xIdempotencyKey] Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can\&#39;t double-charge the customer. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDetailedTransaction(createDetailedTransactionRequest: CreateDetailedTransactionRequest, xIdempotencyKey?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDetailedTransaction(createDetailedTransactionRequest, xIdempotencyKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.createDetailedTransaction']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a payment transaction
         * @param {CreateTransactionRequest} createTransactionRequest 
         * @param {string} [xIdempotencyKey] Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can\&#39;t double-charge the customer. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTransaction(createTransactionRequest: CreateTransactionRequest, xIdempotencyKey?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTransaction(createTransactionRequest, xIdempotencyKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.createTransaction']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Retrieve a single transaction
         * @param {string} transactionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTransaction(transactionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTransaction(transactionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.getTransaction']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List the merchant\'s transactions (newest first)
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {TransactionStatus} [status] 
         * @param {CryptoSymbol} [crypto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTransactions(limit?: number, offset?: number, status?: TransactionStatus, crypto?: CryptoSymbol, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListTransactions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTransactions(limit, offset, status, crypto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.listTransactions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TransactionsApi - factory interface
 * @export
 */
export const TransactionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransactionsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create an itemized transaction (Professional/Enterprise plans)
         * @param {TransactionsApiCreateDetailedTransactionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDetailedTransaction(requestParameters: TransactionsApiCreateDetailedTransactionRequest, options?: RawAxiosRequestConfig): AxiosPromise<TransactionEnvelope> {
            return localVarFp.createDetailedTransaction(requestParameters.createDetailedTransactionRequest, requestParameters.xIdempotencyKey, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a payment transaction
         * @param {TransactionsApiCreateTransactionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTransaction(requestParameters: TransactionsApiCreateTransactionRequest, options?: RawAxiosRequestConfig): AxiosPromise<TransactionEnvelope> {
            return localVarFp.createTransaction(requestParameters.createTransactionRequest, requestParameters.xIdempotencyKey, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieve a single transaction
         * @param {TransactionsApiGetTransactionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransaction(requestParameters: TransactionsApiGetTransactionRequest, options?: RawAxiosRequestConfig): AxiosPromise<TransactionEnvelope> {
            return localVarFp.getTransaction(requestParameters.transactionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List the merchant\'s transactions (newest first)
         * @param {TransactionsApiListTransactionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTransactions(requestParameters: TransactionsApiListTransactionsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ListTransactions200Response> {
            return localVarFp.listTransactions(requestParameters.limit, requestParameters.offset, requestParameters.status, requestParameters.crypto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createDetailedTransaction operation in TransactionsApi.
 * @export
 * @interface TransactionsApiCreateDetailedTransactionRequest
 */
export interface TransactionsApiCreateDetailedTransactionRequest {
    /**
     * 
     * @type {CreateDetailedTransactionRequest}
     * @memberof TransactionsApiCreateDetailedTransaction
     */
    readonly createDetailedTransactionRequest: CreateDetailedTransactionRequest

    /**
     * Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can\&#39;t double-charge the customer. 
     * @type {string}
     * @memberof TransactionsApiCreateDetailedTransaction
     */
    readonly xIdempotencyKey?: string
}

/**
 * Request parameters for createTransaction operation in TransactionsApi.
 * @export
 * @interface TransactionsApiCreateTransactionRequest
 */
export interface TransactionsApiCreateTransactionRequest {
    /**
     * 
     * @type {CreateTransactionRequest}
     * @memberof TransactionsApiCreateTransaction
     */
    readonly createTransactionRequest: CreateTransactionRequest

    /**
     * Optional unique key for a create request (e.g. a UUID). A retried create with the same key returns the original transaction instead of creating a duplicate — send it on every create so a network retry can\&#39;t double-charge the customer. 
     * @type {string}
     * @memberof TransactionsApiCreateTransaction
     */
    readonly xIdempotencyKey?: string
}

/**
 * Request parameters for getTransaction operation in TransactionsApi.
 * @export
 * @interface TransactionsApiGetTransactionRequest
 */
export interface TransactionsApiGetTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof TransactionsApiGetTransaction
     */
    readonly transactionId: string
}

/**
 * Request parameters for listTransactions operation in TransactionsApi.
 * @export
 * @interface TransactionsApiListTransactionsRequest
 */
export interface TransactionsApiListTransactionsRequest {
    /**
     * 
     * @type {number}
     * @memberof TransactionsApiListTransactions
     */
    readonly limit?: number

    /**
     * 
     * @type {number}
     * @memberof TransactionsApiListTransactions
     */
    readonly offset?: number

    /**
     * 
     * @type {TransactionStatus}
     * @memberof TransactionsApiListTransactions
     */
    readonly status?: TransactionStatus

    /**
     * 
     * @type {CryptoSymbol}
     * @memberof TransactionsApiListTransactions
     */
    readonly crypto?: CryptoSymbol
}

/**
 * TransactionsApi - object-oriented interface
 * @export
 * @class TransactionsApi
 * @extends {BaseAPI}
 */
export class TransactionsApi extends BaseAPI {
    /**
     * 
     * @summary Create an itemized transaction (Professional/Enterprise plans)
     * @param {TransactionsApiCreateDetailedTransactionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public createDetailedTransaction(requestParameters: TransactionsApiCreateDetailedTransactionRequest, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).createDetailedTransaction(requestParameters.createDetailedTransactionRequest, requestParameters.xIdempotencyKey, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a payment transaction
     * @param {TransactionsApiCreateTransactionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public createTransaction(requestParameters: TransactionsApiCreateTransactionRequest, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).createTransaction(requestParameters.createTransactionRequest, requestParameters.xIdempotencyKey, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Retrieve a single transaction
     * @param {TransactionsApiGetTransactionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public getTransaction(requestParameters: TransactionsApiGetTransactionRequest, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).getTransaction(requestParameters.transactionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List the merchant\'s transactions (newest first)
     * @param {TransactionsApiListTransactionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public listTransactions(requestParameters: TransactionsApiListTransactionsRequest = {}, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).listTransactions(requestParameters.limit, requestParameters.offset, requestParameters.status, requestParameters.crypto, options).then((request) => request(this.axios, this.basePath));
    }
}



